### ISSUE TITLE
虽然单词是技术相关的，可是释义就完全不对了

### ISSUE THREAD

**Issue by ooking** [kkyon/Simple-IT-English#2]
做这个事情出发点非常好，不过呢，释义不完全不是针对技术的
爬了这么多回来可是没用，随便举些例子
android n. 机器人 [医] 男性样的
static n. 静电, 静电干扰
token n. 表征, 记号, 代币

虽然我英文很渣，但上面这些翻译实在是误人子弟

还有像 instance 常用的都查不到，好失望

翻译看得出是直接通过一般翻译API译的，是否可以找到一个计算机词典再去翻译

**Comment by kkyon** [comment]
目标是用来背单词，不是用来当词字典用。其中3千多个简单单词从列表删除，减少记忆范围。
推荐：把生成的ank文件导入 anki软件，可以随时测试。 非常好用。如果这些单词都能记住，词汇量应该是在2万多左右。
